optimizer:
  name: "Muon"
  lr: 0.001
  betas: [0.9, 0.999]
  weight_decay: 0.01
  eps: 1e-8

  orthogonal_update:
    enabled: true
    projection_method: "newton-schulz"
    update_freq: 100      
    warmup_iters: 500     

  mixed_precision:
    master_weights: true   
    grad_scaler: 
      init_scale: 65536.0
      growth_interval: 2000

  conflict_resolution:
    method: "gradient_projection"
    cos_threshold: -0.5    
    projection_rate: 0.7