
model:
  name: "MuonAD-Base"
  latent_dim: 768         
  attention_heads: 8       
  dropout: 0.1
  activation: "gelu"      
  norm_type: "layer_norm" 
  
  unet:
    in_channels: 4       
    out_channels: 4
    num_blocks: 3         
    channel_mult: [1,2,4] 

  diffusion:
    timesteps: 1000      
    beta_schedule: "linear"
    loss_type: "hybrid"   